sudo: required
services:
  - docker

before_install:
  - docker build -t fangweiwei/complex-docker -f ./client/Dockerfile.dev ./client
  - docker build myotherproject

script:
  - docker run myotherproject runmytests
  - docker run fangweiwei/complex-docker npm test -- --coverage

after_success:
  - docker build -t fangweiwei/multi-client ./client 
  - docker build -t fangweiwei/multi-nginx ./nginx
  - docker build -t fangweiwei/multi-server ./server
  - docker build -t fangweiwei/multi-worker ./worker


#login docker cli




