sudo: required
services:
  - docker

before_install:
  - docker build -t fangweiwei/complex-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run fangweiwei/complex-docker npm test -- --coverage

after_success:
  - docker build -t fangweiwei/multi-client ./client 
  - docker build -t fangweiwei/multi-nginx ./nginx
  - docker build -t fangweiwei/multi-server ./server
  - docker build -t fangweiwei/multi-worker ./worker
  # login docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push fangweiwei/multi-client
  - docker push fangweiwei/multi-nginx
  - docker push fangweiwei/multi-server
  - docker push fangweiwei/multi-worker

